databases:
  - name: myApi
    databaseName: myApi
    user: myApi

services:
  - type: web
    name: myApi
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myApi.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myApi
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4